version: '3'
services:
  gtr:
    image: michaelf34/infinity:latest
    command: --model-name-or-path "sentence-transformers/gtr-t5-base" --port 7997
    ports:
      - "7997:7997"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
